services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "{$POSTGRES_PASSWORD}"
      POSTGRES_DB: "{$APP_NAME}"
      POSTGRES_USER: "{$POSTGRES_USER}"
    restart: always
    expose: [5432]

  spring-backend:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
    ports:
      - "8080:8080"
